#
#-------------------------------------------------------------#
#  创建者：https://v2rayse.com
#  创建时间：2024-03-07 19:35:14
#  模版：ACL4SSR_Online_Full
#  节点数量：1
#-------------------------------------------------------------#
#
mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
#dns:
#  enabled: true
#  nameserver:
#    - 119.29.29.29
#    - 223.5.5.5
#  fallback:
#    - 8.8.8.8
#    - 8.8.4.4
#    - tls://1.0.0.1:853
#    - tls://dns.google:853
proxies:
  - {"type":"vmess","name":"local","http-opts":{"path":["/local"]},"server":"127.0.0.1","port":44331,"uuid":"105a4832-b208-4bfa-b619-a8d1dfa1c3c1","alterId":0,"cipher":"auto","network":"http"}

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - ls
  - name: "Ads"
    type: select
    proxies:
      - REJECT
      - PROXY
      - DIRECT
  - name: "Apple"
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: "Telegram"
    type: select
    proxies:
      - PROXY
  - name: "YouTube"
    type: select
    proxies:
      - PROXY
  - name: "GlobalMedia"
    type: select
    proxies:
      - PROXY
  - name: "Steam"
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: "Others"
    type: select
    proxies:
      - PROXY
      - DIRECT

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  streaming:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.yaml"
    path: ./ruleset/globalmedia.yaml
    interval: 86400
  
  steam:
    type: http
    behavior: classical
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml'
    path: ./ruleset/steam.yaml
    interval: 86400

  steamCN:
    type: http
    behavior: classical
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml'
    path: ./ruleset/steamCN.yaml
    interval: 86400
    
  youtube:
    type: http
    behavior: classical
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml'
    path: ./ruleset/youtube.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,Ads
  - RULE-SET,icloud,Apple
  - RULE-SET,apple,Apple
  - RULE-SET,youtube,YouTube
  - RULE-SET,streaming,GlobalMedia
  - RULE-SET,steamCN,DIRECT
  - RULE-SET,steam,Steam
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,telegramcidr,Telegram
  - RULE-SET,lancidr,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Others